name: mysql
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: sminrana <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mysql1: ^0.17.1

dev_dependencies:
  test: ^1.0.0
