name: Create zip file in dart
description: A sample command-line application to create zip file
version: 1.0.0
homepage: https://flutterframework.com/

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  archive: ^3.1.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
